-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 22:02:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todolist` DEFAULT CHARACTER SET utf8mb4 ;
USE `todolist` ;

-- -----------------------------------------------------
-- Table `todolist`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nivel` CHAR(1) NOT NULL,
  `foto` VARCHAR(150) NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolist`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`plano` (
  `idplano` INT UNSIGNED NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `descricao` TEXT NOT NULL,
  `datacadastro` DATETIME NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`idplano`, `usuarios_id`),
  INDEX `fk_plano_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_plano_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `todolist`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolist`.`tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`tarefas` (
  `idtarefas` INT NOT NULL,
  `nometarefa` TEXT(50) NOT NULL,
  `descricao` TEXT NOT NULL,
  `prioridade` VARCHAR(10) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `data` DATETIME NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`idtarefas`, `usuarios_id`),
  INDEX `fk_tarefas_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_tarefas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `todolist`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolist`.`paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`paginas` (
  `idpaginas` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idpaginas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
